version: '2.4'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn todo_app.main:app --reload'
    volumes:
      - .:/todo_app
    ports:
      - 8008:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5437:5432'

volumes:
  postgres_data: